# Generated by Django 5.0.2 on 2024-07-01 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_remove_transfer_user_transfer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='account_number',
            new_name='accountnumber',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transferdate',
        ),
        migrations.AddField(
            model_name='transfer',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='purpose',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
