# Generated by Django 5.0.2 on 2024-07-01 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_rename_account_number_transfer_accountnumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='account_number',
            new_name='accountnumber',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='charge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='purpose',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
